// Copyright 2022 jack (@waffle87)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP22
#define I2C1_SCL_PIN GP23

#define MOUSEKEY_INTERVAL 16

//#define SPLIT_LAYER_STATE_ENABLE
//#define SPLIT_OLED_ENABLE
#define OLED_BRIGHTNESS 0
#define OLED_TIMEOUT 10000

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define ENABLE_RGBLIGHT_MODE_STATIC_LIGHT
#define TAPPING_TOGGLE 2
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
#define ENCODER_RESOLUTION 2
#define SPLIT_WATCHDOG_ENABLE   // Oprava nefunkční klávesnice po přepojení dokiny
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 2000
#define EE_HANDS